name: "My composite action"
description: "Checks out the repository and does something"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          node_modules
          /home/runner/.cache/Cypress
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}