name: "My composite action"
description: "Checks out the repository and does something"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}