services:
  next:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    command: npm run dev

  db:
    image: mariadb:10.6
    restart: always
    environment:
      MARIADB_DATABASE: cube
      MARIADB_USER: cube
      MARIADB_PASSWORD: cube