services:
  next:
    image: ghcr.io/alexboyere/next-cypress-app:latest
    restart: always
    ports:
      - 3000:3000
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock