on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
      - uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm run start
          browser: firefox
          headed: false