on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: cypress-io/github-action@v5
         with:
           build: npm run build
           start: npm run start
       - uses: actions/upload-artifact@v3
         if: ${{ always() }}
         with:
           name: cypress-videos
           path: cypress/videos